<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Nullable>enable</Nullable>
        <TargetFramework>net9.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
      <PackageReference Include="LibGit2Sharp-SSH" Version="1.0.22" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.11" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    </ItemGroup>

</Project>
